### ISSUE TITLE
task 1 failed - "ngroup should be less than or equal to the number of observations"

### ISSUE THREAD

**Issue by ThomasPouplin** [WMBEdmands/MetMSLine#3]
Guys,

Very strange issue here.
Depending on my input file, the LoessSmooth function works well ... or not.
When it doesn't I got this "ngroup should be less than or equal to the number of observations" message.

I've tried to use the working input file as a template to only copy/paste peak areas from other files but without any success so far.

Has someone encountered this issue before ? And how did you manage to fix it ?
I've attached my xlsx file (just need to save as csv) in case you'd like to try.

Thanks for the answers.

Best regards,

Thomas
[Swath_Pool_Posi_BLKs_from Template_V3 (no norm).xlsx](https://github.com/WMBEdmands/MetMSLine/files/840280/Swath_Pool_Posi_BLKs_from.Template_V3.no.norm.xlsx)

**Comment by WMBEdmands** [comment]
This is a loess function error message which I have seen in the past. Thank you for the peak table file I will attempt to replicate and debug.

**Comment by WMBEdmands** [comment]
Initial thought before I test your file. If the names of your sample and qc columns contain spaces or hyphens for instance these are converted to periods when reading the file from a csv. Make sure the names are correct. This might account for the discrepancy.

**Comment by ThomasPouplin** [comment]
Thanks for your reply. Actually names of samples and QC work in another file I used for testing METMSLine (my template). But using real data, I've got this error. I tried to track from where with R debug but I'm an R user with very little experience and got lost. I'll try with different names and see.

**Comment by ThomasPouplin** [comment]
I've just tried but still unsuccessful  - same message error ... 
I'm running R 3.3.3 64 bits (tried 3.3.2 but similar message) on R studio.

I have attached a different file, but using the exact same format. This one works ... and I've got no clue why.

Any help would be greatly appreciated ... The QC drift correction using this script is truly a game changer when analysing my samples. I need it to work !

[CELL_NP_Posi_Raw matrix.xlsx](https://github.com/WMBEdmands/MetMSLine/files/860342/CELL_NP_Posi_Raw.matrix.xlsx)

**Comment by WMBEdmands** [comment]
FYI, I have been out of office but I am now testing out your files. I may have spotted a bug in the tableCheckRead function. I will let you know as soon as I have fixed and tested. Thanks for drawing this to my attention.

**Comment by ThomasPouplin** [comment]
Dear Will,

Thanks a lot for taking your time to do this. Much appreciated !!!

Best regards,

Thomas

**Comment by WMBEdmands** [comment]
Not at all, it's really important to make sure it's working properly and handling errors properly for all users. Thanks for testing it out and for being patient with me getting back to you.
 
One thing I noticed is the second row of both of the LC-MS feature tables you supplied are the acquisition run order. I had to remove this before saving as a csv or alternatively it can be removed after read.csv in your R session (i.e. `peakTable <- peakTable[-2, ]`. Each row (excluding the top header row) should only represent an LC-MS feature.  

I have just pushed the updates to the MetMSLine repo (v1.1.0).
Try these lines and let me know if they work for you:

`################## start R code ##########################`
`devtools::install_github('WMBEdmands/MetMSLine')`
`# assuming it installs ok`
`# check the version is v1.1.0`
`packageVersion('MetMSLine')`
`library('MetMSLine')`
`# Read in your example peak table "Swath_Pool_Posi_BLKs_from Template_V3 (no norm).xlsx" saved as a csv`
`peakTable <- read.csv('Swath_Pool_Posi_BLKs_from Template_V3 (no norm).csv', header=TRUE, stringsAsFactors = FALSE)`
`# sample names (based on your example peak table "Swath_Pool_Posi_BLKs_from Template_V3 (no norm).xlsx")`
`sampNames <- colnames(peakTable)[grep('^Sample_', colnames(peakTable))]`
`# qc names (based on your example peak table "Swath_Pool_Posi_BLKs_from Template_V3 (no norm).xlsx")`
`qcNames <- colnames(peakTable)[grep('^QC_', colnames(peakTable))]`
`# zero fill`
`peakTable <- zeroFill(peakTable, c(sampNames, qcNames))`
`# loess smooth (single threaded)`
`peakTable <- loessSmooth(peakTable, sampNames, qcNames, nCores=NULL, outputDir=getwd(), smoothSpan=NULL)`
`# loess smooth (parallel)`
`peakTable <- loessSmooth(peakTable, sampNames, qcNames, nCores=parallel::detectCores(), outputDir=getwd(), smoothSpan=NULL)`
`# loess smooth fixed smoothing span (parallel)`
`peakTable <- loessSmooth(peakTable, sampNames, qcNames, nCores=parallel::detectCores(), outputDir=getwd(), smoothSpan=0.8)`
`################## end R code ##########################`

I have sured up some of the error handling and changed how the number of cross-validation folds and the optimum smoothing span parameter are selected for example. Hopefully it will now be more robust. The default is 7-fold cross validation and this was causing an error in your case where you have only 5 pooled quality controls. I have also added a while loop to select the optimal smoothing span parameter in the event of any loess errors. 

If you wish to use a fixed smoothing span parameter (see argument `smoothSpan`, e.g. `smoothSpan=0.8`) rather than the feature-by-feature cross-validated smoothing span parameter (default).

I have also added a progress bar for parallel computations and the ability to generate plots for every LC-MS feature supplied (see argument `outputDir`). The default is not to generate the png files which is faster however if a path to a directory to save the plots is supplied to the loessSmooth function then a new sub-directory will be created "loessSmooth" and the plots will be saved in there.

This will generate plots such as the one shown below (this is the 72nd LC-MS feature from your first table "Swath_Pool_Posi_BLKs_from Template_V3 (no norm).xlsx" which is numbered as 71 in the first column). If you have many thousands of features then bare in mind it may take some time to complete and output all the plots. It may be worth running this function in parallel to save yourself time (try e.g. `nCores=parallel::detectCores()`).

![eic_71](https://cloud.githubusercontent.com/assets/4737960/24429132/9af10fe8-13c5-11e7-925f-89b7e45d0c40.png)

The function outputs a 2-paneled plot for every feature in your table (it uses the first column as the unique identifier/EIC number to name each plot), the first plot shows the loess fit to the raw QC data (with values between QC injections cubic spline interpolated) and then the effect of the loess adjustment  is shown in the second plot. The feature is adjusted by multiplying the peak area/height by the deviation of the interpolated loess fit from the curves median value. In this way the peak areas/heights can be preserved rather than by simply dividing the peak areas/heights by the curve as is presented in Dunn _et. al._ 2011 http://www.nature.com/nprot/journal/v6/n7/full/nprot.2011.335.html.   
I personally find this useful as there is no loss of information downstream.

**Comment by ThomasPouplin** [comment]
Thanks a lot Will !

The new update works beautifully (it says version 1.1.2) - all sorted for me. 
I really like the fact that "natural" intensities are preserved after the Loess correction and individual features can be plotted.

You gave us a fantastic package which will be fully integrated in my lipidomics platform.

Once again, thanks for the quick and effective support you gave me.

With my best wishes,

Thomas

**Comment by WMBEdmands** [comment]
I'm really pleased you are finding it useful. :) Don't forget to cite the paper. `citation('MetMSLine')` 
It is version 1.1.2 now as there were a couple of additional patches I had to make to the `preProc` function and it's documentation. Just to forewarn you sometimes highly negative/skewed values can be generated when using the `loessSmooth` function these are usually few in number but seem to occur when an outlying QC signal intensity is extremely low for example. It is definitely worth visualizing these plots in particular. These variables are also highlighted by a logical column "negVals" in the `loessSmooth` output table. 
You may also find the `preProc` function useful as it is a convenient wrapper function for all of the pre-processing functions (with a suggested order of optional steps):

1. zero filling (see: `zeroFill`).
2. signal normalization (optional, see: `signalNorm`).
3. pooled QC-based loess smoothing (optional, see: `loessSmooth`).
4. blank subtraction (see: `blankSub`).
5. Coefficient of variation calculation and filtration (optional, see: `cvCalc`).
6. log transformation (see: `logTrans`).

Apologies for the plug but the metabolite annotation aspects discussed in the original MetMSLine manuscript (which were in a basic script form) have now been supplanted by [compMS2Miner](https://github.com/WMBEdmands/compMS2Miner) maybe this package will be useful for your work flow also?

**Comment by ThomasPouplin** [comment]
Thanks Will,

I also tested successfully the preProc function and it works well under 1.1.2 version of MetMSLine. Very useful in removing false positive peaks from blanks injections.
I’ve added a line code to remove any molecular features with a NegVals (very few actually) in the newly generated matrix.

I’m into your compMS2Miner package, it will hopefully help a lot, as I have mostly unknown lipids in my experiements.

Don’t worry for citations, you won’t be forgotten !

Best regards,

Thomas
